
const techTopics = [
  
  {
    id: "javascript",
    name: "JavaScript",
    icon: "🟨",
    color: "bg-yellow-500",
    category: "Programming",
    topics: [
      { id: "js-fundamentals", name: "Fundamentals" },
      { id: "js-dom", name: "DOM Manipulation" },
      { id: "js-async", name: "Asynchronous JS" },
      { id: "js-es6", name: "ES6+" },
      { id: "js-promises", name: "Promises & Async/Await" },
      { id: "js-closures", name: "Closures" },
      { id: "js-hoisting", name: "Hoisting" },
      { id: "js-scope", name: "Scope & Context" },
      { id: "js-prototypes", name: "Prototypes" },
      { id: "js-modules", name: "Modules" },
      { id: "js-error-handling", name: "Error Handling" },
      { id: "js-testing", name: "Testing (Jest, Mocha)" },
    ],
  },
  {
    id: "python",
    name: "Python",
    icon: "🐍",
    color: "bg-green-600",
    category: "Programming",
    topics: [
      { id: "py-basics", name: "Basics" },
      { id: "py-oops", name: "OOP" },
      { id: "py-data-structures", name: "Data Structures" },
      { id: "py-web", name: "Web Frameworks" },
      { id: "py-threading", name: "Threading" },
      { id: "py-decorators", name: "Decorators" },
      { id: "py-generators", name: "Generators & Iterators" },
      { id: "py-exception-handling", name: "Exception Handling" },
      { id: "py-file-io", name: "File I/O" },
      { id: "py-regex", name: "Regular Expressions" },
      { id: "py-modules-packages", name: "Modules & Packages" },
      { id: "py-testing", name: "Testing (unittest, pytest)" },
    ],
  },
  {
    id: "java",
    name: "Java",
    icon: "☕",
    color: "bg-orange-600",
    category: "Programming",
    topics: [
      { id: "java-oops", name: "OOP" },
      { id: "java-collections", name: "Collections" },
      { id: "java-threads", name: "Multithreading" },
      { id: "java-stream", name: "Stream API" },
      { id: "java-exception-handling", name: "Exception Handling" },
      { id: "java-generics", name: "Generics" },
      { id: "java-annotations", name: "Annotations" },
      { id: "java-reflection", name: "Reflection" },
      { id: "java-io", name: "I/O Streams" },
      { id: "java-jdbc", name: "JDBC" },
      { id: "java-lambda", name: "Lambda Expressions" },
      { id: "java-design-patterns", name: "Design Patterns" },
    ],
  },
  { 
    id: "cpp", 
    name: "C++", 
    icon: "⚡", 
    color: "bg-blue-600", 
    category: "Programming", 
    topics: [
      { id: "cpp-basics", name: "Basics & Syntax" },
      { id: "cpp-oops", name: "Object-Oriented Programming" },
      { id: "cpp-pointers", name: "Pointers & References" },
      { id: "cpp-memory", name: "Memory Management" },
      { id: "cpp-stl", name: "Standard Template Library" },
      { id: "cpp-templates", name: "Templates" },
      { id: "cpp-inheritance", name: "Inheritance & Polymorphism" },
      { id: "cpp-operator-overloading", name: "Operator Overloading" },
      { id: "cpp-file-handling", name: "File Handling" },
      { id: "cpp-exception-handling", name: "Exception Handling" },
      { id: "cpp-multithreading", name: "Multithreading" },
      { id: "cpp-smart-pointers", name: "Smart Pointers" },
    ] 
  },
  { 
    id: "csharp", 
    name: "C#", 
    icon: "💜", 
    color: "bg-purple-600", 
    category: "Programming", 
    topics: [
      { id: "csharp-basics", name: "Basics & Syntax" },
      { id: "csharp-oops", name: "Object-Oriented Programming" },
      { id: "csharp-collections", name: "Collections & Generics" },
      { id: "csharp-linq", name: "LINQ" },
      { id: "csharp-async", name: "Async/Await" },
      { id: "csharp-delegates", name: "Delegates & Events" },
      { id: "csharp-exception-handling", name: "Exception Handling" },
      { id: "csharp-reflection", name: "Reflection" },
      { id: "csharp-attributes", name: "Attributes" },
      { id: "csharp-file-io", name: "File I/O" },
      { id: "csharp-memory", name: "Memory Management" },
      { id: "csharp-entity-framework", name: "Entity Framework" },
    ] 
  },
  { 
    id: "go", 
    name: "Go", 
    icon: "🐹", 
    color: "bg-cyan-600", 
    category: "Programming", 
    topics: [
      { id: "go-basics", name: "Basics & Syntax" },
      { id: "go-goroutines", name: "Goroutines" },
      { id: "go-channels", name: "Channels" },
      { id: "go-interfaces", name: "Interfaces" },
      { id: "go-structs", name: "Structs & Methods" },
      { id: "go-error-handling", name: "Error Handling" },
      { id: "go-packages", name: "Packages & Modules" },
      { id: "go-testing", name: "Testing" },
      { id: "go-json", name: "JSON Handling" },
      { id: "go-http", name: "HTTP & Web Services" },
      { id: "go-concurrency", name: "Concurrency Patterns" },
      { id: "go-performance", name: "Performance & Optimization" },
    ] 
  },
  { 
    id: "rust", 
    name: "Rust", 
    icon: "🦀", 
    color: "bg-orange-700", 
    category: "Programming", 
    topics: [
      { id: "rust-basics", name: "Basics & Syntax" },
      { id: "rust-ownership", name: "Ownership & Borrowing" },
      { id: "rust-structs-enums", name: "Structs & Enums" },
      { id: "rust-pattern-matching", name: "Pattern Matching" },
      { id: "rust-error-handling", name: "Error Handling" },
      { id: "rust-traits", name: "Traits" },
      { id: "rust-lifetimes", name: "Lifetimes" },
      { id: "rust-generics", name: "Generics" },
      { id: "rust-concurrency", name: "Concurrency" },
      { id: "rust-macros", name: "Macros" },
      { id: "rust-cargo", name: "Cargo & Crates" },
      { id: "rust-unsafe", name: "Unsafe Rust" },
    ] 
  },
  { 
    id: "typescript", 
    name: "TypeScript", 
    icon: "🔷", 
    color: "bg-blue-500", 
    category: "Programming", 
    topics: [
      { id: "ts-basics", name: "Basics & Type System" },
      { id: "ts-interfaces", name: "Interfaces" },
      { id: "ts-classes", name: "Classes" },
      { id: "ts-generics", name: "Generics" },
      { id: "ts-unions-intersections", name: "Union & Intersection Types" },
      { id: "ts-decorators", name: "Decorators" },
      { id: "ts-modules", name: "Modules & Namespaces" },
      { id: "ts-advanced-types", name: "Advanced Types" },
      { id: "ts-mapped-types", name: "Mapped Types" },
      { id: "ts-conditional-types", name: "Conditional Types" },
      { id: "ts-config", name: "TypeScript Configuration" },
      { id: "ts-migration", name: "JavaScript to TypeScript Migration" },
    ] 
  },
  { 
    id: "ruby", 
    name: "Ruby", 
    icon: "💎", 
    color: "bg-red-600", 
    category: "Programming", 
    topics: [
      { id: "ruby-basics", name: "Basics & Syntax" },
      { id: "ruby-oops", name: "Object-Oriented Programming" },
      { id: "ruby-blocks", name: "Blocks, Procs & Lambdas" },
      { id: "ruby-modules", name: "Modules & Mixins" },
      { id: "ruby-metaprogramming", name: "Metaprogramming" },
      { id: "ruby-gems", name: "Gems & Bundler" },
      { id: "ruby-io", name: "File I/O" },
      { id: "ruby-regex", name: "Regular Expressions" },
      { id: "ruby-testing", name: "Testing (RSpec, Minitest)" },
      { id: "ruby-threading", name: "Threading & Concurrency" },
      { id: "ruby-dsl", name: "Domain Specific Languages" },
      { id: "ruby-performance", name: "Performance Optimization" },
    ] 
  },
  { 
    id: "php", 
    name: "PHP", 
    icon: "🐘", 
    color: "bg-purple-700", 
    category: "Programming", 
    topics: [
      { id: "php-basics", name: "Basics & Syntax" },
      { id: "php-oops", name: "Object-Oriented Programming" },
      { id: "php-arrays", name: "Arrays & Functions" },
      { id: "php-forms", name: "Forms & Validation" },
      { id: "php-sessions", name: "Sessions & Cookies" },
      { id: "php-database", name: "Database Connectivity" },
      { id: "php-file-handling", name: "File Handling" },
      { id: "php-error-handling", name: "Error Handling" },
      { id: "php-composer", name: "Composer & Packages" },
      { id: "php-namespaces", name: "Namespaces" },
      { id: "php-traits", name: "Traits" },
      { id: "php-security", name: "Security Best Practices" },
    ] 
  },
  { 
    id: "scala", 
    name: "Scala", 
    icon: "⚙️", 
    color: "bg-indigo-600", 
    category: "Programming", 
    topics: [
      { id: "scala-basics", name: "Basics & Syntax" },
      { id: "scala-functional", name: "Functional Programming" },
      { id: "scala-oops", name: "Object-Oriented Programming" },
      { id: "scala-collections", name: "Collections" },
      { id: "scala-pattern-matching", name: "Pattern Matching" },
      { id: "scala-traits", name: "Traits & Mixins" },
      { id: "scala-case-classes", name: "Case Classes" },
      { id: "scala-futures", name: "Futures & Concurrency" },
      { id: "scala-implicits", name: "Implicits" },
      { id: "scala-akka", name: "Akka Framework" },
      { id: "scala-spark", name: "Apache Spark" },
      { id: "scala-sbt", name: "SBT Build Tool" },
    ] 
  },
  { 
    id: "dart", 
    name: "Dart", 
    icon: "🎯", 
    color: "bg-blue-400", 
    category: "Programming", 
    topics: [
      { id: "dart-basics", name: "Basics & Syntax" },
      { id: "dart-oops", name: "Object-Oriented Programming" },
      { id: "dart-functions", name: "Functions & Methods" },
      { id: "dart-collections", name: "Collections & Iterables" },
      { id: "dart-async", name: "Asynchronous Programming" },
      { id: "dart-streams", name: "Streams" },
      { id: "dart-isolates", name: "Isolates" },
      { id: "dart-packages", name: "Packages & Libraries" },
      { id: "dart-generics", name: "Generics" },
      { id: "dart-mixins", name: "Mixins" },
      { id: "dart-null-safety", name: "Null Safety" },
      { id: "dart-testing", name: "Testing" },
    ] 
  },
  { 
    id: "perl", 
    name: "Perl", 
    icon: "🦪", 
    color: "bg-pink-600", 
    category: "Programming", 
    topics: [
      { id: "perl-basics", name: "Basics & Syntax" },
      { id: "perl-regex", name: "Regular Expressions" },
      { id: "perl-references", name: "References & Data Structures" },
      { id: "perl-modules", name: "Modules & Packages" },
      { id: "perl-oops", name: "Object-Oriented Programming" },
      { id: "perl-file-handling", name: "File Handling" },
      { id: "perl-cpan", name: "CPAN & Libraries" },
      { id: "perl-dbi", name: "Database Programming (DBI)" },
      { id: "perl-web", name: "Web Programming" },
      { id: "perl-testing", name: "Testing" },
      { id: "perl-system", name: "System Administration" },
      { id: "perl-bioinformatics", name: "Bioinformatics" },
    ] 
  },
  { 
    id: "haskell", 
    name: "Haskell", 
    icon: "📐", 
    color: "bg-green-700", 
    category: "Programming", 
    topics: [
      { id: "haskell-basics", name: "Basics & Syntax" },
      { id: "haskell-functions", name: "Functions & Recursion" },
      { id: "haskell-types", name: "Type System" },
      { id: "haskell-lists", name: "Lists & List Comprehensions" },
      { id: "haskell-higher-order", name: "Higher-Order Functions" },
      { id: "haskell-monads", name: "Monads" },
      { id: "haskell-functors", name: "Functors & Applicatives" },
      { id: "haskell-io", name: "Input/Output" },
      { id: "haskell-modules", name: "Modules" },
      { id: "haskell-laziness", name: "Lazy Evaluation" },
      { id: "haskell-cabal", name: "Cabal & Stack" },
      { id: "haskell-testing", name: "Testing (QuickCheck)" },
    ] 
  },
  { 
    id: "elixir", 
    name: "Elixir", 
    icon: "🔮", 
    color: "bg-purple-500", 
    category: "Programming", 
    topics: [
      { id: "elixir-basics", name: "Basics & Syntax" },
      { id: "elixir-pattern-matching", name: "Pattern Matching" },
      { id: "elixir-processes", name: "Processes & Actors" },
      { id: "elixir-otp", name: "OTP (Open Telecom Platform)" },
      { id: "elixir-genserver", name: "GenServer" },
      { id: "elixir-supervisor", name: "Supervisors" },
      { id: "elixir-phoenix", name: "Phoenix Framework" },
      { id: "elixir-ets", name: "ETS & DETS" },
      { id: "elixir-macros", name: "Macros" },
      { id: "elixir-mix", name: "Mix Build Tool" },
      { id: "elixir-testing", name: "Testing (ExUnit)" },
      { id: "elixir-fault-tolerance", name: "Fault Tolerance" },
    ] 
  },
  { 
    id: "clojure", 
    name: "Clojure", 
    icon: "🔗", 
    color: "bg-green-600", 
    category: "Programming", 
    topics: [
      { id: "clojure-basics", name: "Basics & Syntax" },
      { id: "clojure-data-structures", name: "Data Structures" },
      { id: "clojure-functions", name: "Functions & Closures" },
      { id: "clojure-sequences", name: "Sequences" },
      { id: "clojure-macros", name: "Macros" },
      { id: "clojure-state", name: "State Management" },
      { id: "clojure-concurrency", name: "Concurrency" },
      { id: "clojure-java-interop", name: "Java Interoperability" },
      { id: "clojure-protocols", name: "Protocols & Multimethods" },
      { id: "clojure-lein", name: "Leiningen" },
      { id: "clojure-testing", name: "Testing" },
      { id: "clojure-web", name: "Web Development (Ring/Compojure)" },
    ] 
  },

  
  { 
    id: "html", 
    name: "HTML", 
    icon: "🌐", 
    color: "bg-red-500", 
    category: "Web", 
    topics: [
      { id: "html-basics", name: "Basics & Structure" },
      { id: "html-forms", name: "Forms & Input Elements" },
      { id: "html-semantic", name: "Semantic HTML" },
      { id: "html-multimedia", name: "Images, Audio & Video" },
      { id: "html-tables", name: "Tables" },
      { id: "html-accessibility", name: "Accessibility (ARIA)" },
      { id: "html5-features", name: "HTML5 Features" },
      { id: "html-canvas", name: "Canvas API" },
      { id: "html-svg", name: "SVG" },
      { id: "html-web-storage", name: "Web Storage" },
      { id: "html-geolocation", name: "Geolocation API" },
      { id: "html-drag-drop", name: "Drag & Drop API" },
    ] 
  },
  { 
    id: "css", 
    name: "CSS", 
    icon: "🎨", 
    color: "bg-blue-400", 
    category: "Web", 
    topics: [
      { id: "css-basics", name: "Basics & Selectors" },
      { id: "css-box-model", name: "Box Model" },
      { id: "css-flexbox", name: "Flexbox" },
      { id: "css-grid", name: "CSS Grid" },
      { id: "css-positioning", name: "Positioning" },
      { id: "css-responsive", name: "Responsive Design" },
      { id: "css-animations", name: "Animations & Transitions" },
      { id: "css-preprocessors", name: "Preprocessors (Sass, Less)" },
      { id: "css-frameworks", name: "Frameworks (Bootstrap, Tailwind)" },
      { id: "css-modules", name: "CSS Modules" },
      { id: "css-variables", name: "Custom Properties" },
      { id: "css-architecture", name: "CSS Architecture (BEM, OOCSS)" },
    ] 
  },
  { 
    id: "react", 
    name: "React.js", 
    icon: "⚛️", 
    color: "bg-cyan-500", 
    category: "Web", 
    topics: [
      { id: "react-basics", name: "Components & JSX" },
      { id: "react-hooks", name: "Hooks" },
      { id: "react-state", name: "State Management" },
      { id: "react-props", name: "Props & Events" },
      { id: "react-lifecycle", name: "Component Lifecycle" },
      { id: "react-routing", name: "React Router" },
      { id: "react-context", name: "Context API" },
      { id: "react-redux", name: "Redux" },
      { id: "react-forms", name: "Forms & Validation" },
      { id: "react-testing", name: "Testing (Jest, React Testing Library)" },
      { id: "react-performance", name: "Performance Optimization" },
      { id: "react-patterns", name: "Design Patterns" },
    ] 
  },
  { 
    id: "nextjs", 
    name: "Next.js", 
    icon: "⚫", 
    color: "bg-gray-800", 
    category: "Web", 
    topics: [
      { id: "nextjs-basics", name: "Pages & Routing" },
      { id: "nextjs-ssr", name: "Server-Side Rendering" },
      { id: "nextjs-ssg", name: "Static Site Generation" },
      { id: "nextjs-api-routes", name: "API Routes" },
      { id: "nextjs-dynamic-routing", name: "Dynamic Routing" },
      { id: "nextjs-image-optimization", name: "Image Optimization" },
      { id: "nextjs-deployment", name: "Deployment" },
      { id: "nextjs-middleware", name: "Middleware" },
      { id: "nextjs-auth", name: "Authentication" },
      { id: "nextjs-performance", name: "Performance" },
      { id: "nextjs-data-fetching", name: "Data Fetching" },
      { id: "nextjs-internationalization", name: "Internationalization" },
    ] 
  },
  { 
    id: "vue", 
    name: "Vue.js", 
    icon: "💚", 
    color: "bg-green-500", 
    category: "Web", 
    topics: [
      { id: "vue-basics", name: "Basics & Templates" },
      { id: "vue-components", name: "Components" },
      { id: "vue-directives", name: "Directives" },
      { id: "vue-data-binding", name: "Data Binding" },
      { id: "vue-events", name: "Event Handling" },
      { id: "vue-lifecycle", name: "Lifecycle Hooks" },
      { id: "vue-router", name: "Vue Router" },
      { id: "vue-vuex", name: "Vuex State Management" },
      { id: "vue-composition", name: "Composition API" },
      { id: "vue-forms", name: "Forms & Validation" },
      { id: "vue-testing", name: "Testing" },
      { id: "vue-nuxt", name: "Nuxt.js Framework" },
    ] 
  },
  { 
    id: "angular", 
    name: "Angular", 
    icon: "🅰️", 
    color: "bg-red-600", 
    category: "Web", 
    topics: [
      { id: "angular-basics", name: "Components & Templates" },
      { id: "angular-typescript", name: "TypeScript Integration" },
      { id: "angular-services", name: "Services & Dependency Injection" },
      { id: "angular-routing", name: "Routing & Navigation" },
      { id: "angular-forms", name: "Forms (Reactive & Template-driven)" },
      { id: "angular-http", name: "HTTP Client" },
      { id: "angular-observables", name: "RxJS & Observables" },
      { id: "angular-directives", name: "Directives & Pipes" },
      { id: "angular-lifecycle", name: "Lifecycle Hooks" },
      { id: "angular-testing", name: "Testing (Jasmine, Karma)" },
      { id: "angular-animations", name: "Animations" },
      { id: "angular-cli", name: "Angular CLI" },
    ] 
  },
  { 
    id: "svelte", 
    name: "Svelte", 
    icon: "🔥", 
    color: "bg-orange-500", 
    category: "Web", 
    topics: [
      { id: "svelte-basics", name: "Basics & Components" },
      { id: "svelte-reactivity", name: "Reactivity" },
      { id: "svelte-props", name: "Props & Events" },
      { id: "svelte-stores", name: "Stores" },
      { id: "svelte-lifecycle", name: "Lifecycle" },
      { id: "svelte-animations", name: "Animations & Transitions" },
      { id: "svelte-routing", name: "Routing" },
      { id: "svelte-styling", name: "Styling" },
      { id: "svelte-actions", name: "Actions" },
      { id: "svelte-sveltekit", name: "SvelteKit" },
      { id: "svelte-testing", name: "Testing" },
      { id: "svelte-deployment", name: "Deployment" },
    ] 
  },
  { 
    id: "gatsby", 
    name: "Gatsby", 
    icon: "🌿", 
    color: "bg-purple-400", 
    category: "Web", 
    topics: [
      { id: "gatsby-basics", name: "Static Site Generation" },
      { id: "gatsby-graphql", name: "GraphQL Data Layer" },
      { id: "gatsby-pages", name: "Pages & Routing" },
      { id: "gatsby-plugins", name: "Plugins" },
      { id: "gatsby-images", name: "Image Processing" },
      { id: "gatsby-cms", name: "Headless CMS Integration" },
      { id: "gatsby-deployment", name: "Deployment" },
      { id: "gatsby-performance", name: "Performance Optimization" },
      { id: "gatsby-pwa", name: "Progressive Web Apps" },
      { id: "gatsby-themes", name: "Themes" },
      { id: "gatsby-styling", name: "Styling Solutions" },
      { id: "gatsby-e-commerce", name: "E-commerce Integration" },
    ] 
  },
  { 
    id: "ember", 
    name: "Ember.js", 
    icon: "🐹", 
    color: "bg-red-400", 
    category: "Web", 
    topics: [
      { id: "ember-basics", name: "Components & Templates" },
      { id: "ember-routing", name: "Routing" },
      { id: "ember-models", name: "Models & Ember Data" },
      { id: "ember-controllers", name: "Controllers" },
      { id: "ember-services", name: "Services" },
      { id: "ember-actions", name: "Actions & Events" },
      { id: "ember-helpers", name: "Helpers" },
      { id: "ember-addons", name: "Addons" },
      { id: "ember-testing", name: "Testing" },
      { id: "ember-cli", name: "Ember CLI" },
      { id: "ember-fastboot", name: "FastBoot (SSR)" },
      { id: "ember-deployment", name: "Deployment" },
    ] 
  },
  { 
    id: "jquery", 
    name: "jQuery", 
    icon: "💙", 
    color: "bg-blue-600", 
    category: "Web", 
    topics: [
      { id: "jquery-basics", name: "Basics & Selectors" },
      { id: "jquery-dom", name: "DOM Manipulation" },
      { id: "jquery-events", name: "Event Handling" },
      { id: "jquery-effects", name: "Effects & Animations" },
      { id: "jquery-ajax", name: "AJAX" },
      { id: "jquery-forms", name: "Form Handling" },
      { id: "jquery-plugins", name: "Plugins" },
      { id: "jquery-ui", name: "jQuery UI" },
      { id: "jquery-mobile", name: "jQuery Mobile" },
      { id: "jquery-performance", name: "Performance Best Practices" },
      { id: "jquery-migration", name: "Migration to Modern JS" },
      { id: "jquery-deferred", name: "Deferred Objects" },
    ] 
  },

  
  { 
    id: "nodejs", 
    name: "Node.js", 
    icon: "🟢", 
    color: "bg-green-600", 
    category: "Backend", 
    topics: [
      { id: "nodejs-basics", name: "Basics & Event Loop" },
      { id: "nodejs-modules", name: "Modules & NPM" },
      { id: "nodejs-fs", name: "File System" },
      { id: "nodejs-http", name: "HTTP Module" },
      { id: "nodejs-streams", name: "Streams" },
      { id: "nodejs-events", name: "Events" },
      { id: "nodejs-buffer", name: "Buffers" },
      { id: "nodejs-async", name: "Asynchronous Programming" },
      { id: "nodejs-clustering", name: "Clustering" },
      { id: "nodejs-debugging", name: "Debugging" },
      { id: "nodejs-testing", name: "Testing (Mocha, Jest)" },
      { id: "nodejs-security", name: "Security Best Practices" },
    ] 
  },
  { 
    id: "express", 
    name: "Express.js", 
    icon: "🚂", 
    color: "bg-gray-700", 
    category: "Backend", 
    topics: [
      { id: "express-basics", name: "Basics & Routing" },
      { id: "express-middleware", name: "Middleware" },
      { id: "express-routing", name: "Advanced Routing" },
      { id: "express-templates", name: "Template Engines" },
      { id: "express-static", name: "Static Files" },
      { id: "express-error-handling", name: "Error Handling" },
      { id: "express-validation", name: "Input Validation" },
      { id: "express-auth", name: "Authentication & Authorization" },
      { id: "express-sessions", name: "Sessions & Cookies" },
      { id: "express-database", name: "Database Integration" },
      { id: "express-security", name: "Security (Helmet, CORS)" },
      { id: "express-testing", name: "Testing" },
    ] 
  },
  { 
    id: "django", 
    name: "Django", 
    icon: "🎸", 
    color: "bg-green-700", 
    category: "Backend", 
    topics: [
      { id: "django-basics", name: "Models, Views, Templates" },
      { id: "django-orm", name: "ORM & Database" },
      { id: "django-admin", name: "Admin Interface" },
      { id: "django-forms", name: "Forms & Validation" },
      { id: "django-auth", name: "User Authentication" },
      { id: "django-middleware", name: "Middleware" },
      { id: "django-rest", name: "Django REST Framework" },
      { id: "django-testing", name: "Testing" },
      { id: "django-deployment", name: "Deployment" },
      { id: "django-security", name: "Security" },
      { id: "django-signals", name: "Signals" },
      { id: "django-caching", name: "Caching" },
    ] 
  },
  { 
    id: "flask", 
    name: "Flask", 
    icon: "🌶️", 
    color: "bg-red-400", 
    category: "Backend", 
    topics: [
      { id: "flask-basics", name: "Basics & Routing" },
      { id: "flask-templates", name: "Templates (Jinja2)" },
      { id: "flask-forms", name: "Forms & Validation" },
      { id: "flask-database", name: "Database Integration" },
      { id: "flask-auth", name: "User Authentication" },
      { id: "flask-blueprints", name: "Blueprints" },
      { id: "flask-restful", name: "RESTful APIs" },
      { id: "flask-testing", name: "Testing" },
      { id: "flask-deployment", name: "Deployment" },
      { id: "flask-extensions", name: "Extensions" },
      { id: "flask-sessions", name: "Sessions & Cookies" },
      { id: "flask-error-handling", name: "Error Handling" },
    ] 
  },
  { 
    id: "fastapi", 
    name: "FastAPI", 
    icon: "⚡", 
    color: "bg-teal-600", 
    category: "Backend", 
    topics: [
      { id: "fastapi-basics", name: "Basics & Path Operations" },
      { id: "fastapi-pydantic", name: "Pydantic Models" },
      { id: "fastapi-validation", name: "Request Validation" },
      { id: "fastapi-dependency", name: "Dependency Injection" },
      { id: "fastapi-auth", name: "Authentication & Security" },
      { id: "fastapi-database", name: "Database Integration" },
      { id: "fastapi-middleware", name: "Middleware" },
      { id: "fastapi-testing", name: "Testing" },
      { id: "fastapi-async", name: "Async Operations" },
      { id: "fastapi-websockets", name: "WebSockets" },
      { id: "fastapi-deployment", name: "Deployment" },
      { id: "fastapi-documentation", name: "Automatic Documentation" },
    ] 
  },
  { 
    id: "spring", 
    name: "Spring Boot", 
    icon: "🍃", 
    color: "bg-green-600", 
    category: "Backend", 
    topics: [
      { id: "spring-basics", name: "Basics & Auto-configuration" },
      { id: "spring-mvc", name: "Spring MVC" },
      { id: "spring-data", name: "Spring Data JPA" },
      { id: "spring-security", name: "Spring Security" },
      { id: "spring-rest", name: "RESTful Web Services" },
      { id: "spring-actuator", name: "Spring Boot Actuator" },
      { id: "spring-testing", name: "Testing" },
      { id: "spring-profiles", name: "Profiles & Configuration" },
      { id: "spring-microservices", name: "Microservices" },
      { id: "spring-cloud", name: "Spring Cloud" },
      { id: "spring-batch", name: "Spring Batch" },
      { id: "spring-deployment", name: "Deployment" },
    ] 
  },
  { 
    id: "laravel", 
    name: "Laravel", 
    icon: "🎯", 
    color: "bg-red-600", 
    category: "Backend", 
    topics: [
      { id: "laravel-basics", name: "MVC & Routing" },
      { id: "laravel-eloquent", name: "Eloquent ORM" },
      { id: "laravel-blade", name: "Blade Templates" },
      { id: "laravel-auth", name: "Authentication & Authorization" },
      { id: "laravel-middleware", name: "Middleware" },
      { id: "laravel-validation", name: "Form Validation" },
      { id: "laravel-queue", name: "Queues & Jobs" },
      { id: "laravel-mail", name: "Mail & Notifications" },
      { id: "laravel-artisan", name: "Artisan Console" },
      { id: "laravel-testing", name: "Testing (PHPUnit)" },
      { id: "laravel-api", name: "API Development" },
      { id: "laravel-deployment", name: "Deployment" },
    ] 
  },
  { 
    id: "ruby-on-rails", 
    name: "Ruby on Rails", 
    icon: "💎", 
    color: "bg-red-500", 
    category: "Backend", 
    topics: [
      { id: "rails-mvc", name: "MVC Architecture" },
      { id: "rails-routing", name: "Routing" },
      { id: "rails-active-record", name: "Active Record" },
      { id: "rails-views", name: "Views & ERB" },
      { id: "rails-controllers", name: "Controllers" },
      { id: "rails-migrations", name: "Migrations" },
      { id: "rails-validations", name: "Validations" },
      { id: "rails-associations", name: "Associations" },
      { id: "rails-testing", name: "Testing (RSpec, Minitest)" },
      { id: "rails-api", name: "API Development" },
      { id: "rails-deployment", name: "Deployment" },
      { id: "rails-security", name: "Security Best Practices" },
    ] 
  },
  { 
    id: "aspnet", 
    name: "ASP.NET", 
    icon: "🅰️", 
    color: "bg-purple-700", 
    category: "Backend", 
    topics: [
      { id: "aspnet-mvc", name: "MVC Pattern" },
      { id: "aspnet-web-api", name: "Web API" },
      { id: "aspnet-core", name: "ASP.NET Core" },
      { id: "aspnet-entity-framework", name: "Entity Framework" },
      { id: "aspnet-identity", name: "Identity & Authentication" },
      { id: "aspnet-middleware", name: "Middleware" },
      { id: "aspnet-dependency-injection", name: "Dependency Injection" },
      { id: "aspnet-razor", name: "Razor Pages" },
      { id: "aspnet-signalr", name: "SignalR" },
      { id: "aspnet-testing", name: "Testing" },
      { id: "aspnet-deployment", name: "Deployment" },
      { id: "aspnet-security", name: "Security" },
    ] 
  },
  { 
    id: "graphql", 
    name: "GraphQL", 
    icon: "🔺", 
    color: "bg-pink-600", 
    category: "Backend", 
    topics: [
      { id: "graphql-basics", name: "Schema & Types" },
      { id: "graphql-queries", name: "Queries" },
      { id: "graphql-mutations", name: "Mutations" },
      { id: "graphql-subscriptions", name: "Subscriptions" },
      { id: "graphql-resolvers", name: "Resolvers" },
      { id: "graphql-apollo", name: "Apollo Server" },
      { id: "graphql-relay", name: "Relay" },
      { id: "graphql-authentication", name: "Authentication" },
      { id: "graphql-caching", name: "Caching" },
      { id: "graphql-testing", name: "Testing" },
      { id: "graphql-federation", name: "Federation" },
      { id: "graphql-performance", name: "Performance Optimization" },
    ] 
  },

  
  { 
    id: "sql", 
    name: "SQL", 
    icon: "🗄️", 
    color: "bg-blue-700", 
    category: "Database", 
    topics: [
      { id: "sql-basics", name: "Basic Queries (SELECT, INSERT, UPDATE, DELETE)" },
      { id: "sql-joins", name: "Joins" },
      { id: "sql-functions", name: "Aggregate Functions" },
      { id: "sql-subqueries", name: "Subqueries" },
      { id: "sql-indexes", name: "Indexes" },
      { id: "sql-views", name: "Views" },
      { id: "sql-stored-procedures", name: "Stored Procedures" },
      { id: "sql-triggers", name: "Triggers" },
      { id: "sql-transactions", name: "Transactions" },
      { id: "sql-normalization", name: "Database Normalization" },
      { id: "sql-performance", name: "Query Optimization" },
      { id: "sql-window-functions", name: "Window Functions" },
    ] 
  },
  { 
    id: "mysql", 
    name: "MySQL", 
    icon: "🐬", 
    color: "bg-orange-600", 
    category: "Database", 
    topics: [
      { id: "mysql-installation", name: "Installation & Setup" },
      { id: "mysql-data-types", name: "Data Types" },
      { id: "mysql-storage-engines", name: "Storage Engines" },
      { id: "mysql-replication", name: "Replication" },
      { id: "mysql-partitioning", name: "Partitioning" },
      { id: "mysql-backup", name: "Backup & Recovery" },
      { id: "mysql-security", name: "Security" },
      { id: "mysql-performance", name: "Performance Tuning" },
      { id: "mysql-clustering", name: "MySQL Cluster" },
      { id: "mysql-json", name: "JSON Data Type" },
      { id: "mysql-full-text", name: "Full-Text Search" },
      { id: "mysql-administration", name: "Database Administration" },
    ] 
  },
  { 
    id: "postgresql", 
    name: "PostgreSQL", 
    icon: "🐘", 
    color: "bg-blue-800", 
    category: "Database", 
    topics: [
      { id: "postgresql-advanced-types", name: "Advanced Data Types" },
      { id: "postgresql-jsonb", name: "JSONB" },
      { id: "postgresql-arrays", name: "Arrays" },
      { id: "postgresql-extensions", name: "Extensions" },
      { id: "postgresql-functions", name: "Functions & Procedures" },
      { id: "postgresql-triggers", name: "Triggers" },
      { id: "postgresql-replication", name: "Replication" },
      { id: "postgresql-partitioning", name: "Table Partitioning" },
      { id: "postgresql-full-text", name: "Full-Text Search" },
      { id: "postgresql-performance", name: "Performance Tuning" },
      { id: "postgresql-administration", name: "Administration" },
      { id: "postgresql-gis", name: "PostGIS (Spatial Data)" },
    ] 
  },
  { 
    id: "mongodb", 
    name: "MongoDB", 
    icon: "🍃", 
    color: "bg-green-700", 
    category: "Database", 
    topics: [
      { id: "mongodb-documents", name: "Documents & Collections" },
      { id: "mongodb-queries", name: "Queries & Filters" },
      { id: "mongodb-aggregation", name: "Aggregation Pipeline" },
      { id: "mongodb-indexing", name: "Indexing" },
      { id: "mongodb-replication", name: "Replica Sets" },
      { id: "mongodb-sharding", name: "Sharding" },
      { id: "mongodb-transactions", name: "Transactions" },
      { id: "mongodb-schema", name: "Schema Design" },
      { id: "mongodb-mongoose", name: "Mongoose ODM" },
      { id: "mongodb-atlas", name: "MongoDB Atlas" },
      { id: "mongodb-security", name: "Security" },
      { id: "mongodb-performance", name: "Performance Optimization" },
    ] 
  },
  { 
    id: "redis", 
    name: "Redis", 
    icon: "🔴", 
    color: "bg-red-600", 
    category: "Database", 
    topics: [
      { id: "redis-data-structures", name: "Data Structures" },
      { id: "redis-caching", name: "Caching Strategies" },
      { id: "redis-pub-sub", name: "Pub/Sub" },
      { id: "redis-transactions", name: "Transactions" },
      { id: "redis-lua-scripting", name: "Lua Scripting" },
      { id: "redis-persistence", name: "Persistence" },
      { id: "redis-clustering", name: "Clustering" },
      { id: "redis-sentinel", name: "Redis Sentinel" },
      { id: "redis-streams", name: "Redis Streams" },
      { id: "redis-modules", name: "Redis Modules" },
      { id: "redis-security", name: "Security" },
      { id: "redis-monitoring", name: "Monitoring & Debugging" },
    ] 
  },
  { 
    id: "sqlite", 
    name: "SQLite", 
    icon: "📦", 
    color: "bg-gray-500", 
    category: "Database", 
    topics: [
      { id: "sqlite-basics", name: "Basics & Setup" },
      { id: "sqlite-data-types", name: "Data Types" },
      { id: "sqlite-constraints", name: "Constraints" },
      { id: "sqlite-indexes", name: "Indexes" },
      { id: "sqlite-views", name: "Views" },
      { id: "sqlite-triggers", name: "Triggers" },
      { id: "sqlite-transactions", name: "Transactions" },
      { id: "sqlite-fts", name: "Full-Text Search" },
      { id: "sqlite-json", name: "JSON Support" },
      { id: "sqlite-performance", name: "Performance Optimization" },
      { id: "sqlite-backup", name: "Backup & Recovery" },
      { id: "sqlite-extensions", name: "Extensions" },
    ] 
  },
  { 
    id: "cassandra", 
    name: "Cassandra", 
    icon: "🎰", 
    color: "bg-purple-600", 
    category: "Database", 
    topics: [
      { id: "cassandra-architecture", name: "Architecture" },
      { id: "cassandra-data-modeling", name: "Data Modeling" },
      { id: "cassandra-cql", name: "CQL (Cassandra Query Language)" },
      { id: "cassandra-partitioning", name: "Partitioning" },
      { id: "cassandra-replication", name: "Replication" },
      { id: "cassandra-consistency", name: "Consistency Levels" },
      { id: "cassandra-clustering", name: "Clustering" },
      { id: "cassandra-performance", name: "Performance Tuning" },
      { id: "cassandra-monitoring", name: "Monitoring" },
      { id: "cassandra-security", name: "Security" },
      { id: "cassandra-backup", name: "Backup & Recovery" },
      { id: "cassandra-migration", name: "Data Migration" },
    ] 
  },
  { 
    id: "firebase", 
    name: "Firebase", 
    icon: "🔥", 
    color: "bg-orange-400", 
    category: "Database", 
    topics: [
      { id: "firebase-realtime-db", name: "Realtime Database" },
      { id: "firebase-firestore", name: "Cloud Firestore" },
      { id: "firebase-auth", name: "Authentication" },
      { id: "firebase-hosting", name: "Hosting" },
      { id: "firebase-functions", name: "Cloud Functions" },
      { id: "firebase-storage", name: "Cloud Storage" },
      { id: "firebase-messaging", name: "Cloud Messaging" },
      { id: "firebase-analytics", name: "Analytics" },
      { id: "firebase-security", name: "Security Rules" },
      { id: "firebase-performance", name: "Performance Monitoring" },
      { id: "firebase-remote-config", name: "Remote Config" },
      { id: "firebase-crashlytics", name: "Crashlytics" },
    ] 
  },

  
  { 
    id: "react-native", 
    name: "React Native", 
    icon: "📱", 
    color: "bg-blue-500", 
    category: "Mobile", 
    topics: [
      { id: "rn-basics", name: "Components & Navigation" },
      { id: "rn-styling", name: "Styling & Flexbox" },
      { id: "rn-state", name: "State Management" },
      { id: "rn-navigation", name: "React Navigation" },
      { id: "rn-native-modules", name: "Native Modules" },
      { id: "rn-apis", name: "Device APIs" },
      { id: "rn-storage", name: "Local Storage" },
      { id: "rn-networking", name: "Networking" },
      { id: "rn-testing", name: "Testing" },
      { id: "rn-deployment", name: "Deployment" },
      { id: "rn-performance", name: "Performance Optimization" },
      { id: "rn-expo", name: "Expo Framework" },
    ] 
  },
  { 
    id: "flutter", 
    name: "Flutter", 
    icon: "🦋", 
    color: "bg-blue-400", 
    category: "Mobile", 
    topics: [
      { id: "flutter-widgets", name: "Widgets" },
      { id: "flutter-layouts", name: "Layouts" },
      { id: "flutter-state", name: "State Management" },
      { id: "flutter-navigation", name: "Navigation & Routing" },
      { id: "flutter-animations", name: "Animations" },
      { id: "flutter-networking", name: "HTTP & Networking" },
      { id: "flutter-storage", name: "Local Storage" },
      { id: "flutter-plugins", name: "Plugins & Packages" },
      { id: "flutter-testing", name: "Testing" },
      { id: "flutter-deployment", name: "Deployment" },
      { id: "flutter-performance", name: "Performance" },
      { id: "flutter-platform-channels", name: "Platform Channels" },
    ] 
  },
  { 
    id: "kotlin", 
    name: "Kotlin", 
    icon: "🟣", 
    color: "bg-purple-500", 
    category: "Mobile", 
    topics: [
      { id: "kotlin-basics", name: "Syntax & Basics" },
      { id: "kotlin-android-basics", name: "Android Development Basics" },
      { id: "kotlin-activities", name: "Activities & Fragments" },
      { id: "kotlin-ui", name: "UI Development" },
      { id: "kotlin-data", name: "Data Storage" },
      { id: "kotlin-networking", name: "Networking" },
      { id: "kotlin-architecture", name: "Architecture Components" },
      { id: "kotlin-jetpack", name: "Jetpack Compose" },
      { id: "kotlin-testing", name: "Testing" },
      { id: "kotlin-coroutines", name: "Coroutines" },
      { id: "kotlin-multiplatform", name: "Kotlin Multiplatform" },
      { id: "kotlin-deployment", name: "App Deployment" },
    ] 
  },
  { 
    id: "swift", 
    name: "Swift", 
    icon: "🍎", 
    color: "bg-orange-500", 
    category: "Mobile", 
    topics: [
      { id: "swift-basics", name: "Syntax & Basics" },
      { id: "swift-ios-basics", name: "iOS Development Basics" },
      { id: "swift-ui", name: "UIKit & SwiftUI" },
      { id: "swift-mvc", name: "MVC Architecture" },
      { id: "swift-data", name: "Core Data" },
      { id: "swift-networking", name: "Networking" },
      { id: "swift-autolayout", name: "Auto Layout" },
      { id: "swift-navigation", name: "Navigation" },
      { id: "swift-testing", name: "Testing" },
      { id: "swift-memory", name: "Memory Management" },
      { id: "swift-app-store", name: "App Store Deployment" },
      { id: "swift-combine", name: "Combine Framework" },
    ] 
  },
  { 
    id: "java-android", 
    name: "Java (Android)", 
    icon: "🤖", 
    color: "bg-green-600", 
    category: "Mobile", 
    topics: [
      { id: "java-android-basics", name: "Android Development Basics" },
      { id: "java-android-activities", name: "Activities & Intents" },
      { id: "java-android-fragments", name: "Fragments" },
      { id: "java-android-ui", name: "UI Components" },
      { id: "java-android-layouts", name: "Layouts" },
      { id: "java-android-data", name: "Data Storage" },
      { id: "java-android-networking", name: "Networking" },
      { id: "java-android-services", name: "Services & Background Tasks" },
      { id: "java-android-broadcasting", name: "Broadcast Receivers" },
      { id: "java-android-testing", name: "Testing" },
      { id: "java-android-deployment", name: "App Deployment" },
      { id: "java-android-material", name: "Material Design" },
    ] 
  },
  { 
    id: "objective-c", 
    name: "Objective-C", 
    icon: "🍏", 
    color: "bg-green-700", 
    category: "Mobile", 
    topics: [
      { id: "objc-basics", name: "Syntax & Basics" },
      { id: "objc-memory", name: "Memory Management" },
      { id: "objc-classes", name: "Classes & Objects" },
      { id: "objc-protocols", name: "Protocols & Delegates" },
      { id: "objc-categories", name: "Categories & Extensions" },
      { id: "objc-foundation", name: "Foundation Framework" },
      { id: "objc-uikit", name: "UIKit" },
      { id: "objc-mvc", name: "MVC Pattern" },
      { id: "objc-core-data", name: "Core Data" },
      { id: "objc-networking", name: "Networking" },
      { id: "objc-blocks", name: "Blocks" },
      { id: "objc-legacy", name: "Legacy Code Maintenance" },
    ] 
  },

  
  { 
    id: "docker", 
    name: "Docker", 
    icon: "🐳", 
    color: "bg-blue-600", 
    category: "DevOps", 
    topics: [
      { id: "docker-basics", name: "Containers & Images" },
      { id: "docker-dockerfile", name: "Dockerfile" },
      { id: "docker-compose", name: "Docker Compose" },
      { id: "docker-networking", name: "Networking" },
      { id: "docker-volumes", name: "Volumes & Storage" },
      { id: "docker-registry", name: "Docker Registry" },
      { id: "docker-security", name: "Security" },
      { id: "docker-multi-stage", name: "Multi-stage Builds" },
      { id: "docker-swarm", name: "Docker Swarm" },
      { id: "docker-monitoring", name: "Monitoring & Logging" },
      { id: "docker-optimization", name: "Optimization" },
      { id: "docker-troubleshooting", name: "Troubleshooting" },
    ] 
  },
  { 
    id: "kubernetes", 
    name: "Kubernetes", 
    icon: "☸️", 
    color: "bg-blue-700", 
    category: "DevOps", 
    topics: [
      { id: "k8s-architecture", name: "Architecture" },
      { id: "k8s-pods", name: "Pods" },
      { id: "k8s-services", name: "Services" },
      { id: "k8s-deployments", name: "Deployments" },
      { id: "k8s-configmaps", name: "ConfigMaps & Secrets" },
      { id: "k8s-volumes", name: "Volumes" },
      { id: "k8s-networking", name: "Networking" },
      { id: "k8s-ingress", name: "Ingress" },
      { id: "k8s-helm", name: "Helm" },
      { id: "k8s-monitoring", name: "Monitoring" },
      { id: "k8s-security", name: "Security" },
      { id: "k8s-troubleshooting", name: "Troubleshooting" },
    ] 
  },
  { 
    id: "terraform", 
    name: "Terraform", 
    icon: "🌍", 
    color: "bg-green-600", 
    category: "DevOps", 
    topics: [
      { id: "terraform-basics", name: "Basics & HCL" },
      { id: "terraform-providers", name: "Providers" },
      { id: "terraform-resources", name: "Resources" },
      { id: "terraform-variables", name: "Variables" },
      { id: "terraform-modules", name: "Modules" },
      { id: "terraform-state", name: "State Management" },
      { id: "terraform-workspaces", name: "Workspaces" },
      { id: "terraform-remote-state", name: "Remote State" },
      { id: "terraform-provisioners", name: "Provisioners" },
      { id: "terraform-import", name: "Import & Migration" },
      { id: "terraform-best-practices", name: "Best Practices" },
      { id: "terraform-testing", name: "Testing" },
    ] 
  },
  { 
    id: "ansible", 
    name: "Ansible", 
    icon: "🎯", 
    color: "bg-red-600", 
    category: "DevOps", 
    topics: [
      { id: "ansible-basics", name: "Basics & Inventory" },
      { id: "ansible-playbooks", name: "Playbooks" },
      { id: "ansible-modules", name: "Modules" },
      { id: "ansible-variables", name: "Variables" },
      { id: "ansible-conditionals", name: "Conditionals & Loops" },
      { id: "ansible-handlers", name: "Handlers" },
      { id: "ansible-roles", name: "Roles" },
      { id: "ansible-vault", name: "Ansible Vault" },
      { id: "ansible-templates", name: "Templates (Jinja2)" },
      { id: "ansible-galaxy", name: "Ansible Galaxy" },
      { id: "ansible-testing", name: "Testing" },
      { id: "ansible-best-practices", name: "Best Practices" },
    ] 
  },
  { 
    id: "jenkins", 
    name: "Jenkins", 
    icon: "🤖", 
    color: "bg-red-700", 
    category: "DevOps", 
    topics: [
      { id: "jenkins-basics", name: "Basics & Installation" },
      { id: "jenkins-jobs", name: "Jobs & Builds" },
      { id: "jenkins-pipeline", name: "Pipeline as Code" },
      { id: "jenkins-plugins", name: "Plugins" },
      { id: "jenkins-scm", name: "Source Code Management" },
      { id: "jenkins-triggers", name: "Build Triggers" },
      { id: "jenkins-distributed", name: "Distributed Builds" },
      { id: "jenkins-security", name: "Security" },
      { id: "jenkins-monitoring", name: "Monitoring" },
      { id: "jenkins-backup", name: "Backup & Recovery" },
      { id: "jenkins-scripting", name: "Groovy Scripting" },
      { id: "jenkins-integration", name: "Tool Integration" },
    ] 
  },
  { 
    id: "aws", 
    name: "AWS", 
    icon: "☁️", 
    color: "bg-yellow-600", 
    category: "Cloud", 
    topics: [
      { id: "aws-ec2", name: "EC2" },
      { id: "aws-s3", name: "S3" },
      { id: "aws-rds", name: "RDS" },
      { id: "aws-lambda", name: "Lambda" },
      { id: "aws-vpc", name: "VPC" },
      { id: "aws-iam", name: "IAM" },
      { id: "aws-cloudformation", name: "CloudFormation" },
      { id: "aws-api-gateway", name: "API Gateway" },
      { id: "aws-cloudwatch", name: "CloudWatch" },
      { id: "aws-eks", name: "EKS" },
      { id: "aws-route53", name: "Route 53" },
      { id: "aws-security", name: "Security Best Practices" },
    ] 
  },
  { 
    id: "azure", 
    name: "Azure", 
    icon: "🌐", 
    color: "bg-blue-600", 
    category: "Cloud", 
    topics: [
      { id: "azure-vm", name: "Virtual Machines" },
      { id: "azure-storage", name: "Storage Solutions" },
      { id: "azure-sql", name: "Azure SQL Database" },
      { id: "azure-functions", name: "Azure Functions" },
      { id: "azure-app-service", name: "App Service" },
      { id: "azure-aks", name: "Azure Kubernetes Service" },
      { id: "azure-ad", name: "Active Directory" },
      { id: "azure-devops", name: "Azure DevOps" },
      { id: "azure-arm", name: "ARM Templates" },
      { id: "azure-monitor", name: "Azure Monitor" },
      { id: "azure-networking", name: "Networking" },
      { id: "azure-security", name: "Security" },
    ] 
  },
  { 
    id: "gcp", 
    name: "Google Cloud", 
    icon: "🌈", 
    color: "bg-red-500", 
    category: "Cloud", 
    topics: [
      { id: "gcp-compute", name: "Compute Engine" },
      { id: "gcp-storage", name: "Cloud Storage" },
      { id: "gcp-sql", name: "Cloud SQL" },
      { id: "gcp-functions", name: "Cloud Functions" },
      { id: "gcp-app-engine", name: "App Engine" },
      { id: "gcp-gke", name: "Google Kubernetes Engine" },
      { id: "gcp-iam", name: "Identity & Access Management" },
      { id: "gcp-networking", name: "Networking" },
      { id: "gcp-monitoring", name: "Cloud Monitoring" },
      { id: "gcp-deployment", name: "Deployment Manager" },
      { id: "gcp-bigquery", name: "BigQuery" },
      { id: "gcp-security", name: "Security" },
    ] 
  },
  { 
    id: "digitalocean", 
    name: "DigitalOcean", 
    icon: "🐬", 
    color: "bg-blue-500", 
    category: "Cloud", 
    topics: [
      { id: "do-droplets", name: "Droplets" },
      { id: "do-spaces", name: "Spaces" },
      { id: "do-databases", name: "Managed Databases" },
      { id: "do-kubernetes", name: "Kubernetes" },
      { id: "do-app-platform", name: "App Platform" },
      { id: "do-load-balancers", name: "Load Balancers" },
      { id: "do-networking", name: "Networking" },
      { id: "do-monitoring", name: "Monitoring" },
      { id: "do-snapshots", name: "Snapshots & Backups" },
      { id: "do-firewall", name: "Cloud Firewall" },
      { id: "do-volumes", name: "Block Storage" },
      { id: "do-api", name: "API & CLI" },
    ] 
  },
  { 
    id: "openstack", 
    name: "OpenStack", 
    icon: "🔧", 
    color: "bg-gray-700", 
    category: "Cloud", 
    topics: [
      { id: "openstack-architecture", name: "Architecture" },
      { id: "openstack-nova", name: "Nova (Compute)" },
      { id: "openstack-neutron", name: "Neutron (Networking)" },
      { id: "openstack-cinder", name: "Cinder (Block Storage)" },
      { id: "openstack-swift", name: "Swift (Object Storage)" },
      { id: "openstack-keystone", name: "Keystone (Identity)" },
      { id: "openstack-glance", name: "Glance (Image)" },
      { id: "openstack-horizon", name: "Horizon (Dashboard)" },
      { id: "openstack-heat", name: "Heat (Orchestration)" },
      { id: "openstack-deployment", name: "Deployment" },
      { id: "openstack-troubleshooting", name: "Troubleshooting" },
      { id: "openstack-administration", name: "Administration" },
    ] 
  },

  
  { 
    id: "dsa", 
    name: "Data Structures & Algorithms", 
    icon: "🌳", 
    color: "bg-indigo-600", 
    category: "CS Fundamentals", 
    topics: [
      { id: "dsa-arrays", name: "Arrays & Strings" },
      { id: "dsa-linked-lists", name: "Linked Lists" },
      { id: "dsa-stacks-queues", name: "Stacks & Queues" },
      { id: "dsa-trees", name: "Trees & Binary Trees" },
      { id: "dsa-graphs", name: "Graphs" },
      { id: "dsa-hashing", name: "Hashing" },
      { id: "dsa-sorting", name: "Sorting Algorithms" },
      { id: "dsa-searching", name: "Searching Algorithms" },
      { id: "dsa-dynamic-programming", name: "Dynamic Programming" },
      { id: "dsa-greedy", name: "Greedy Algorithms" },
      { id: "dsa-backtracking", name: "Backtracking" },
      { id: "dsa-complexity", name: "Time & Space Complexity" },
    ] 
  },
  { 
    id: "os", 
    name: "Operating Systems", 
    icon: "💻", 
    color: "bg-blue-500", 
    category: "CS Fundamentals", 
    topics: [
      { id: "os-processes", name: "Processes & Threads" },
      { id: "os-scheduling", name: "CPU Scheduling" },
      { id: "os-synchronization", name: "Process Synchronization" },
      { id: "os-deadlocks", name: "Deadlocks" },
      { id: "os-memory", name: "Memory Management" },
      { id: "os-virtual-memory", name: "Virtual Memory" },
      { id: "os-file-systems", name: "File Systems" },
      { id: "os-io", name: "I/O Systems" },
      { id: "os-security", name: "Protection & Security" },
      { id: "os-distributed", name: "Distributed Systems" },
      { id: "os-virtualization", name: "Virtualization" },
      { id: "os-case-studies", name: "Case Studies (Linux, Windows)" },
      { id: "os-problems", name: "Problems in Operating Systems ( numericals )" },
    ] 
  },
  { 
    id: "dbms", 
    name: "Database Management Systems", 
    icon: "🗄️", 
    color: "bg-green-500", 
    category: "CS Fundamentals", 
    topics: [
      { id: "dbms-er-model", name: "ER Model" },
      { id: "dbms-relational-model", name: "Relational Model" },
      { id: "dbms-normalization", name: "Normalization" },
      { id: "dbms-sql", name: "SQL" },
      { id: "dbms-transactions", name: "Transactions" },
      { id: "dbms-concurrency", name: "Concurrency Control" },
      { id: "dbms-recovery", name: "Recovery Systems" },
      { id: "dbms-indexing", name: "Indexing & B-Trees" },
      { id: "dbms-query-processing", name: "Query Processing" },
      { id: "dbms-optimization", name: "Query Optimization" },
      { id: "dbms-distributed", name: "Distributed Databases" },
      { id: "dbms-nosql", name: "NoSQL Databases" },
    ] 
  },
 { 
  id: "cn", 
  name: "Computer Networks", 
  icon: "🌐", 
  color: "bg-cyan-500", 
  category: "CS Fundamentals", 
  topics: [
    { id: "cn-osi-model", name: "OSI Model" },
    { id: "cn-tcp-ip", name: "TCP/IP Protocol Suite" },
    { id: "cn-physical-layer", name: "Physical Layer" },
    { id: "cn-data-link", name: "Data Link Layer" },
    { id: "cn-network-layer", name: "Network Layer" },
    { id: "cn-transport-layer", name: "Transport Layer" },
    { id: "cn-application-layer", name: "Application Layer" },
    { id: "cn-routing", name: "Routing Algorithms" },
    { id: "cn-congestion", name: "Congestion Control" },
    { id: "cn-security", name: "Network Security" },
    { id: "cn-wireless", name: "Wireless Networks" },
    { id: "cn-performance", name: "Network Performance" },
    { id: "cn-numericals", name: "Numericals" }  
  ] 
},

  { 
    id: "compiler", 
    name: "Compiler Design", 
    icon: "🔧", 
    color: "bg-gray-600", 
    category: "CS Fundamentals", 
    topics: [
      { id: "compiler-lexical", name: "Lexical Analysis" },
      { id: "compiler-syntax", name: "Syntax Analysis" },
      { id: "compiler-semantic", name: "Semantic Analysis" },
      { id: "compiler-intermediate", name: "Intermediate Code Generation" },
      { id: "compiler-optimization", name: "Code Optimization" },
      { id: "compiler-target", name: "Target Code Generation" },
      { id: "compiler-symbol-table", name: "Symbol Table" },
      { id: "compiler-error-handling", name: "Error Handling" },
      { id: "compiler-runtime", name: "Runtime Environments" },
      { id: "compiler-parsing", name: "Parsing Techniques" },
      { id: "compiler-automata", name: "Finite Automata" },
      { id: "compiler-grammars", name: "Context-Free Grammars" },
    ] 
  },
  { 
    id: "ai-ml", 
    name: "AI & Machine Learning", 
    icon: "🤖", 
    color: "bg-purple-600", 
    category: "CS Fundamentals", 
    topics: [
      { id: "ml-supervised", name: "Supervised Learning" },
      { id: "ml-unsupervised", name: "Unsupervised Learning" },
      { id: "ml-reinforcement", name: "Reinforcement Learning" },
      { id: "ml-neural-networks", name: "Neural Networks" },
      { id: "ml-deep-learning", name: "Deep Learning" },
      { id: "ml-nlp", name: "Natural Language Processing" },
      { id: "ml-computer-vision", name: "Computer Vision" },
      { id: "ml-feature-engineering", name: "Feature Engineering" },
      { id: "ml-model-evaluation", name: "Model Evaluation" },
      { id: "ml-algorithms", name: "ML Algorithms" },
      { id: "ml-frameworks", name: "ML Frameworks (TensorFlow, PyTorch)" },
      { id: "ml-ethics", name: "AI Ethics" },
    ] 
  },
  { 
    id: "theory-computation", 
    name: "Theory of Computation", 
    icon: "📚", 
    color: "bg-indigo-700", 
    category: "CS Fundamentals", 
    topics: [
      { id: "toc-automata", name: "Finite Automata" },
      { id: "toc-regular", name: "Regular Languages" },
      { id: "toc-context-free", name: "Context-Free Languages" },
      { id: "toc-pushdown", name: "Pushdown Automata" },
      { id: "toc-turing", name: "Turing Machines" },
      { id: "toc-decidability", name: "Decidability" },
      { id: "toc-complexity", name: "Computational Complexity" },
      { id: "toc-p-np", name: "P vs NP Problem" },
      { id: "toc-reductions", name: "Reductions" },
      { id: "toc-space-complexity", name: "Space Complexity" },
      { id: "toc-hierarchy", name: "Chomsky Hierarchy" },
      { id: "toc-pumping-lemma", name: "Pumping Lemma" },
    ] 
  },
  { 
    id: "cryptography", 
    name: "Cryptography", 
    icon: "🔒", 
    color: "bg-purple-700", 
    category: "CS Fundamentals", 
    topics: [
      { id: "crypto-symmetric", name: "Symmetric Cryptography" },
      { id: "crypto-asymmetric", name: "Asymmetric Cryptography" },
      { id: "crypto-hash", name: "Hash Functions" },
      { id: "crypto-digital-signatures", name: "Digital Signatures" },
      { id: "crypto-key-management", name: "Key Management" },
      { id: "crypto-protocols", name: "Cryptographic Protocols" },
      { id: "crypto-pki", name: "Public Key Infrastructure" },
      { id: "crypto-network-security", name: "Network Security" },
      { id: "crypto-attacks", name: "Cryptographic Attacks" },
      { id: "crypto-blockchain", name: "Blockchain Cryptography" },
      { id: "crypto-quantum", name: "Quantum Cryptography" },
      { id: "crypto-implementations", name: "Implementation Security" },
    ] 
  },
  { 
    id: "software-engineering", 
    name: "Software Engineering", 
    icon: "🛠️", 
    color: "bg-blue-700", 
    category: "CS Fundamentals", 
    topics: [
      { id: "se-sdlc", name: "Software Development Life Cycle" },
      { id: "se-requirements", name: "Requirements Engineering" },
      { id: "se-design", name: "Software Design" },
      { id: "se-architecture", name: "Software Architecture" },
      { id: "se-testing", name: "Software Testing" },
      { id: "se-maintenance", name: "Software Maintenance" },
      { id: "se-project-management", name: "Project Management" },
      { id: "se-agile", name: "Agile Methodologies" },
      { id: "se-version-control", name: "Version Control" },
      { id: "se-documentation", name: "Documentation" },
      { id: "se-quality", name: "Software Quality" },
      { id: "se-metrics", name: "Software Metrics" },
    ] 
  },

  
  { 
    id: "oops-python", 
    name: "OOP in Python", 
    icon: "🐍", 
    color: "bg-green-500", 
    category: "OOP", 
    topics: [
      { id: "py-oop-classes", name: "Classes & Objects" },
      { id: "py-oop-inheritance", name: "Inheritance" },
      { id: "py-oop-polymorphism", name: "Polymorphism" },
      { id: "py-oop-encapsulation", name: "Encapsulation" },
      { id: "py-oop-abstraction", name: "Abstraction" },
      { id: "py-oop-magic-methods", name: "Magic Methods" },
      { id: "py-oop-property", name: "Property Decorators" },
      { id: "py-oop-class-methods", name: "Class & Static Methods" },
      { id: "py-oop-multiple-inheritance", name: "Multiple Inheritance" },
      { id: "py-oop-mro", name: "Method Resolution Order" },
      { id: "py-oop-metaclasses", name: "Metaclasses" },
      { id: "py-oop-design-patterns", name: "Design Patterns" },
    ] 
  },
  { 
    id: "oops-java", 
    name: "OOP in Java", 
    icon: "☕", 
    color: "bg-orange-500", 
    category: "OOP", 
    topics: [
      { id: "java-oop-classes", name: "Classes & Objects" },
      { id: "java-oop-inheritance", name: "Inheritance" },
      { id: "java-oop-polymorphism", name: "Polymorphism" },
      { id: "java-oop-encapsulation", name: "Encapsulation" },
      { id: "java-oop-abstraction", name: "Abstraction" },
      { id: "java-oop-interfaces", name: "Interfaces" },
      { id: "java-oop-access-modifiers", name: "Access Modifiers" },
      { id: "java-oop-constructors", name: "Constructors" },
      { id: "java-oop-overriding", name: "Method Overriding" },
      { id: "java-oop-overloading", name: "Method Overloading" },
      { id: "java-oop-final", name: "Final Keyword" },
      { id: "java-oop-design-patterns", name: "Design Patterns" },
    ] 
  },
  { 
    id: "oops-cpp", 
    name: "OOP in C++", 
    icon: "⚡", 
    color: "bg-blue-500", 
    category: "OOP", 
    topics: [
      { id: "cpp-oop-classes", name: "Classes & Objects" },
      { id: "cpp-oop-constructors", name: "Constructors & Destructors" },
      { id: "cpp-oop-inheritance", name: "Inheritance" },
      { id: "cpp-oop-polymorphism", name: "Polymorphism" },
      { id: "cpp-oop-encapsulation", name: "Encapsulation" },
      { id: "cpp-oop-abstraction", name: "Abstraction" },
      { id: "cpp-oop-virtual", name: "Virtual Functions" },
      { id: "cpp-oop-operator-overloading", name: "Operator Overloading" },
      { id: "cpp-oop-friend", name: "Friend Functions & Classes" },
      { id: "cpp-oop-multiple-inheritance", name: "Multiple Inheritance" },
      { id: "cpp-oop-templates", name: "Templates" },
      { id: "cpp-oop-stl", name: "STL & OOP" },
    ] 
  },
  { 
    id: "oops-csharp", 
    name: "OOP in C#", 
    icon: "💜", 
    color: "bg-purple-500", 
    category: "OOP", 
    topics: [
      { id: "cs-oop-classes", name: "Classes & Objects" },
      { id: "cs-oop-inheritance", name: "Inheritance" },
      { id: "cs-oop-polymorphism", name: "Polymorphism" },
      { id: "cs-oop-encapsulation", name: "Encapsulation" },
      { id: "cs-oop-abstraction", name: "Abstraction" },
      { id: "cs-oop-interfaces", name: "Interfaces" },
      { id: "cs-oop-properties", name: "Properties" },
      { id: "cs-oop-indexers", name: "Indexers" },
      { id: "cs-oop-delegates", name: "Delegates & Events" },
      { id: "cs-oop-generics", name: "Generics" },
      { id: "cs-oop-extension-methods", name: "Extension Methods" },
      { id: "cs-oop-design-patterns", name: "Design Patterns" },
    ] 
  },
  { 
    id: "oops-ruby", 
    name: "OOP in Ruby", 
    icon: "💎", 
    color: "bg-red-600", 
    category: "OOP", 
    topics: [
      { id: "ruby-oop-classes", name: "Classes & Objects" },
      { id: "ruby-oop-modules", name: "Modules & Mixins" },
      { id: "ruby-oop-inheritance", name: "Inheritance" },
      { id: "ruby-oop-visibility", name: "Method Visibility" },
      { id: "ruby-oop-attr", name: "Attribute Accessors" },
      { id: "ruby-oop-class-methods", name: "Class Methods & Variables" },
      { id: "ruby-oop-constants", name: "Constants" },
      { id: "ruby-oop-singleton", name: "Singleton Methods" },
      { id: "ruby-oop-metaprogramming", name: "Metaprogramming" },
      { id: "ruby-oop-duck-typing", name: "Duck Typing" },
      { id: "ruby-oop-method-missing", name: "Method Missing" },
      { id: "ruby-oop-design-patterns", name: "Design Patterns" },
    ] 
  },

  
  { 
    id: "git", 
    name: "Git & Version Control", 
    icon: "🌿", 
    color: "bg-orange-600", 
    category: "Tools", 
    topics: [
      { id: "git-basics", name: "Basic Commands" },
      { id: "git-branching", name: "Branching & Merging" },
      { id: "git-remote", name: "Remote Repositories" },
      { id: "git-workflow", name: "Git Workflows" },
      { id: "git-conflicts", name: "Merge Conflicts" },
      { id: "git-rebase", name: "Rebasing" },
      { id: "git-hooks", name: "Git Hooks" },
      { id: "git-submodules", name: "Submodules" },
      { id: "git-advanced", name: "Advanced Git" },
      { id: "git-github", name: "GitHub Features" },
      { id: "git-gitlab", name: "GitLab Features" },
      { id: "git-best-practices", name: "Best Practices" },
    ] 
  },
  { 
    id: "linux", 
    name: "Linux Commands", 
    icon: "🐧", 
    color: "bg-gray-800", 
    category: "Tools", 
    topics: [
      { id: "linux-basics", name: "Basic Commands" },
      { id: "linux-file-system", name: "File System Navigation" },
      { id: "linux-permissions", name: "File Permissions" },
      { id: "linux-text-processing", name: "Text Processing" },
      { id: "linux-process", name: "Process Management" },
      { id: "linux-networking", name: "Networking Commands" },
      { id: "linux-system-info", name: "System Information" },
      { id: "linux-package-management", name: "Package Management" },
      { id: "linux-shell-scripting", name: "Shell Scripting" },
      { id: "linux-cron", name: "Cron Jobs" },
      { id: "linux-logs", name: "Log Files" },
      { id: "linux-performance", name: "Performance Monitoring" },
    ] 
  },
  { 
    id: "testing", 
    name: "Software Testing", 
    icon: "🧪", 
    color: "bg-teal-500", 
    category: "Tools", 
    topics: [
      { id: "testing-fundamentals", name: "Testing Fundamentals" },
      { id: "testing-unit", name: "Unit Testing" },
      { id: "testing-integration", name: "Integration Testing" },
      { id: "testing-e2e", name: "End-to-End Testing" },
      { id: "testing-tdd", name: "Test-Driven Development" },
      { id: "testing-bdd", name: "Behavior-Driven Development" },
      { id: "testing-automation", name: "Test Automation" },
      { id: "testing-performance", name: "Performance Testing" },
      { id: "testing-security", name: "Security Testing" },
      { id: "testing-frameworks", name: "Testing Frameworks" },
      { id: "testing-ci-cd", name: "Testing in CI/CD" },
      { id: "testing-strategies", name: "Testing Strategies" },
    ] 
  },
  { 
    id: "webpack", 
    name: "Webpack", 
    icon: "📦", 
    color: "bg-purple-600", 
    category: "Tools", 
    topics: [
      { id: "webpack-basics", name: "Basics & Configuration" },
      { id: "webpack-loaders", name: "Loaders" },
      { id: "webpack-plugins", name: "Plugins" },
      { id: "webpack-dev-server", name: "Dev Server" },
      { id: "webpack-code-splitting", name: "Code Splitting" },
      { id: "webpack-optimization", name: "Optimization" },
      { id: "webpack-hot-reload", name: "Hot Module Replacement" },
      { id: "webpack-assets", name: "Asset Management" },
      { id: "webpack-production", name: "Production Builds" },
      { id: "webpack-tree-shaking", name: "Tree Shaking" },
      { id: "webpack-source-maps", name: "Source Maps" },
      { id: "webpack-advanced", name: "Advanced Configuration" },
    ] 
  },
  { 
    id: "babel", 
    name: "Babel", 
    icon: "📝", 
    color: "bg-yellow-400", 
    category: "Tools", 
    topics: [
      { id: "babel-basics", name: "Basics & Setup" },
      { id: "babel-presets", name: "Presets" },
      { id: "babel-plugins", name: "Plugins" },
      { id: "babel-config", name: "Configuration" },
      { id: "babel-polyfills", name: "Polyfills" },
      { id: "babel-transforms", name: "Custom Transforms" },
      { id: "babel-webpack", name: "Webpack Integration" },
      { id: "babel-nodejs", name: "Node.js Integration" },
      { id: "babel-react", name: "React & JSX" },
      { id: "babel-typescript", name: "TypeScript Integration" },
      { id: "babel-optimization", name: "Build Optimization" },
      { id: "babel-debugging", name: "Debugging" },
    ] 
  },
  { 
    id: "eslint", 
    name: "ESLint", 
    icon: "🚨", 
    color: "bg-red-500", 
    category: "Tools", 
    topics: [
      { id: "eslint-basics", name: "Basics & Setup" },
      { id: "eslint-rules", name: "Rules Configuration" },
      { id: "eslint-config", name: "Configuration Files" },
      { id: "eslint-presets", name: "Shareable Configs" },
      { id: "eslint-plugins", name: "Plugins" },
      { id: "eslint-custom-rules", name: "Custom Rules" },
      { id: "eslint-integration", name: "IDE Integration" },
      { id: "eslint-ci-cd", name: "CI/CD Integration" },
      { id: "eslint-typescript", name: "TypeScript Support" },
      { id: "eslint-react", name: "React Support" },
      { id: "eslint-vue", name: "Vue.js Support" },
      { id: "eslint-best-practices", name: "Best Practices" },
    ] 
  },
  { 
    id: "prettier", 
    name: "Prettier", 
    icon: "🎨", 
    color: "bg-pink-400", 
    category: "Tools", 
    topics: [
      { id: "prettier-basics", name: "Basics & Setup" },
      { id: "prettier-config", name: "Configuration" },
      { id: "prettier-integration", name: "IDE Integration" },
      { id: "prettier-eslint", name: "ESLint Integration" },
      { id: "prettier-pre-commit", name: "Pre-commit Hooks" },
      { id: "prettier-ci-cd", name: "CI/CD Integration" },
      { id: "prettier-languages", name: "Supported Languages" },
      { id: "prettier-ignore", name: "Ignore Files" },
      { id: "prettier-plugins", name: "Plugins" },
      { id: "prettier-api", name: "Prettier API" },
      { id: "prettier-workflow", name: "Workflow Integration" },
      { id: "prettier-best-practices", name: "Best Practices" },
    ] 
  },
  { 
    id: "jira", 
    name: "Jira", 
    icon: "📋", 
    color: "bg-blue-700", 
    category: "Tools", 
    topics: [
      { id: "jira-basics", name: "Basics & Navigation" },
      { id: "jira-projects", name: "Projects & Issues" },
      { id: "jira-workflows", name: "Workflows" },
      { id: "jira-agile", name: "Agile Boards" },
      { id: "jira-reporting", name: "Reporting & Analytics" },
      { id: "jira-customization", name: "Customization" },
      { id: "jira-automation", name: "Automation Rules" },
      { id: "jira-integrations", name: "Integrations" },
      { id: "jira-permissions", name: "Permissions & Security" },
      { id: "jira-administration", name: "Administration" },
      { id: "jira-api", name: "REST API" },
      { id: "jira-best-practices", name: "Best Practices" },
    ] 
  },
  { 
    id: "postman", 
    name: "Postman", 
    icon: "📬", 
    color: "bg-orange-400", 
    category: "Tools", 
    topics: [
      { id: "postman-basics", name: "Basics & Interface" },
      { id: "postman-requests", name: "Creating Requests" },
      { id: "postman-collections", name: "Collections" },
      { id: "postman-environments", name: "Environments & Variables" },
      { id: "postman-testing", name: "Writing Tests" },
      { id: "postman-scripts", name: "Pre-request Scripts" },
      { id: "postman-automation", name: "Test Automation" },
      { id: "postman-monitoring", name: "API Monitoring" },
      { id: "postman-documentation", name: "API Documentation" },
      { id: "postman-collaboration", name: "Team Collaboration" },
      { id: "postman-ci-cd", name: "CI/CD Integration" },
      { id: "postman-advanced", name: "Advanced Features" },
    ] 
  },

  
  { 
    id: "hadoop", 
    name: "Hadoop", 
    icon: "🐘", 
    color: "bg-green-700", 
    category: "Big Data", 
    topics: [
      { id: "hadoop-architecture", name: "Hadoop Architecture" },
      { id: "hadoop-hdfs", name: "HDFS" },
      { id: "hadoop-mapreduce", name: "MapReduce" },
      { id: "hadoop-yarn", name: "YARN" },
      { id: "hadoop-ecosystem", name: "Hadoop Ecosystem" },
      { id: "hadoop-hive", name: "Apache Hive" },
      { id: "hadoop-pig", name: "Apache Pig" },
      { id: "hadoop-hbase", name: "HBase" },
      { id: "hadoop-sqoop", name: "Sqoop" },
      { id: "hadoop-flume", name: "Flume" },
      { id: "hadoop-oozie", name: "Oozie" },
      { id: "hadoop-administration", name: "Cluster Administration" },
    ] 
  },
  { 
    id: "spark", 
    name: "Apache Spark", 
    icon: "✨", 
    color: "bg-red-600", 
    category: "Big Data", 
    topics: [
      { id: "spark-core", name: "Spark Core" },
      { id: "spark-rdd", name: "RDDs" },
      { id: "spark-dataframes", name: "DataFrames & Datasets" },
      { id: "spark-sql", name: "Spark SQL" },
      { id: "spark-streaming", name: "Spark Streaming" },
      { id: "spark-mllib", name: "MLlib" },
      { id: "spark-graphx", name: "GraphX" },
      { id: "spark-performance", name: "Performance Tuning" },
      { id: "spark-deployment", name: "Deployment Modes" },
      { id: "spark-scala", name: "Spark with Scala" },
      { id: "spark-python", name: "PySpark" },
      { id: "spark-java", name: "Spark with Java" },
    ] 
  },
  { 
    id: "kafka", 
    name: "Apache Kafka", 
    icon: "☕", 
    color: "bg-red-700", 
    category: "Big Data", 
    topics: [
      { id: "kafka-basics", name: "Kafka Basics" },
      { id: "kafka-architecture", name: "Architecture" },
      { id: "kafka-producers", name: "Producers" },
      { id: "kafka-consumers", name: "Consumers" },
      { id: "kafka-topics", name: "Topics & Partitions" },
      { id: "kafka-brokers", name: "Brokers" },
      { id: "kafka-zookeeper", name: "ZooKeeper" },
      { id: "kafka-streams", name: "Kafka Streams" },
      { id: "kafka-connect", name: "Kafka Connect" },
      { id: "kafka-schema-registry", name: "Schema Registry" },
      { id: "kafka-monitoring", name: "Monitoring" },
      { id: "kafka-security", name: "Security" },
    ] 
  },

  
  { 
    id: "solidity", 
    name: "Solidity", 
    icon: "🔷", 
    color: "bg-blue-600", 
    category: "Blockchain", 
    topics: [
      { id: "solidity-basics", name: "Syntax & Basics" },
      { id: "solidity-data-types", name: "Data Types" },
      { id: "solidity-functions", name: "Functions" },
      { id: "solidity-contracts", name: "Contracts" },
      { id: "solidity-inheritance", name: "Inheritance" },
      { id: "solidity-events", name: "Events & Logging" },
      { id: "solidity-modifiers", name: "Modifiers" },
      { id: "solidity-libraries", name: "Libraries" },
      { id: "solidity-assembly", name: "Inline Assembly" },
      { id: "solidity-patterns", name: "Design Patterns" },
      { id: "solidity-security", name: "Security Best Practices" },
      { id: "solidity-testing", name: "Testing & Debugging" },
    ] 
  },
  { 
    id: "ethereum", 
    name: "Ethereum", 
    icon: "⧫", 
    color: "bg-purple-700", 
    category: "Blockchain", 
    topics: [
      { id: "ethereum-basics", name: "Ethereum Fundamentals" },
      { id: "ethereum-evm", name: "Ethereum Virtual Machine" },
      { id: "ethereum-gas", name: "Gas & Transaction Fees" },
      { id: "ethereum-accounts", name: "Accounts & Addresses" },
      { id: "ethereum-web3", name: "Web3.js" },
      { id: "ethereum-metamask", name: "MetaMask Integration" },
      { id: "ethereum-truffle", name: "Truffle Framework" },
      { id: "ethereum-hardhat", name: "Hardhat" },
      { id: "ethereum-ipfs", name: "IPFS Integration" },
      { id: "ethereum-layer2", name: "Layer 2 Solutions" },
      { id: "ethereum-upgrades", name: "Contract Upgrades" },
      { id: "ethereum-oracles", name: "Oracles" },
    ] 
  },

  
  { 
    id: "figma", 
    name: "Figma", 
    icon: "🎨", 
    color: "bg-purple-500", 
    category: "Design", 
    topics: [
      { id: "figma-basics", name: "Interface & Tools" },
      { id: "figma-design", name: "Design Basics" },
      { id: "figma-components", name: "Components & Variants" },
      { id: "figma-auto-layout", name: "Auto Layout" },
      { id: "figma-constraints", name: "Constraints" },
      { id: "figma-styles", name: "Styles & Design Systems" },
      { id: "figma-prototyping", name: "Prototyping" },
      { id: "figma-collaboration", name: "Collaboration" },
      { id: "figma-plugins", name: "Plugins" },
      { id: "figma-handoff", name: "Developer Handoff" },
      { id: "figma-responsive", name: "Responsive Design" },
      { id: "figma-advanced", name: "Advanced Features" },
    ] 
  },
  { 
    id: "adobe-xd", 
    name: "Adobe XD", 
    icon: "✏️", 
    color: "bg-red-600", 
    category: "Design", 
    topics: [
      { id: "xd-basics", name: "Interface & Tools" },
      { id: "xd-design", name: "Design & Layout" },
      { id: "xd-artboards", name: "Artboards & Grids" },
      { id: "xd-components", name: "Components & States" },
      { id: "xd-responsive", name: "Responsive Resize" },
      { id: "xd-prototyping", name: "Prototyping & Interactions" },
      { id: "xd-voice", name: "Voice Prototyping" },
      { id: "xd-collaboration", name: "Sharing & Collaboration" },
      { id: "xd-plugins", name: "Plugins & Integrations" },
      { id: "xd-specs", name: "Design Specs" },
      { id: "xd-assets", name: "Assets & Libraries" },
      { id: "xd-workflow", name: "Design Workflow" },
    ] 
  },
  { 
    id: "sketch", 
    name: "Sketch", 
    icon: "✂️", 
    color: "bg-yellow-500", 
    category: "Design", 
    topics: [
      { id: "sketch-basics", name: "Interface & Tools" },
      { id: "sketch-vectors", name: "Vector Editing" },
      { id: "sketch-symbols", name: "Symbols & Overrides" },
      { id: "sketch-styles", name: "Text & Layer Styles" },
      { id: "sketch-libraries", name: "Libraries" },
      { id: "sketch-prototyping", name: "Prototyping" },
      { id: "sketch-plugins", name: "Plugins" },
      { id: "sketch-cloud", name: "Sketch Cloud" },
      { id: "sketch-handoff", name: "Developer Handoff" },
      { id: "sketch-export", name: "Export & Assets" },
      { id: "sketch-design-systems", name: "Design Systems" },
      { id: "sketch-workflow", name: "Design Workflow" },
    ] 
  },




  
  { id: "quant-number-system", name: "Number System", icon: "🔢", color: "bg-blue-600", category: "Aptitude", topics: [] },
  { id: "quant-hcf-lcm", name: "HCF & LCM", icon: "➗", color: "bg-teal-500", category: "Aptitude", topics: [] },
  { id: "quant-percentages", name: "Percentages", icon: "📊", color: "bg-orange-500", category: "Aptitude", topics: [] },
  { id: "quant-ratios-proportions", name: "Ratios & Proportions", icon: "⚖️", color: "bg-purple-500", category: "Aptitude", topics: [] },
  { id: "quant-average", name: "Averages", icon: "📏", color: "bg-pink-500", category: "Aptitude", topics: [] },
  { id: "quant-mixtures", name: "Mixtures & Alligation", icon: "🥤", color: "bg-green-500", category: "Aptitude", topics: [] },
  { id: "quant-simple-interest", name: "Simple Interest", icon: "💰", color: "bg-yellow-600", category: "Aptitude", topics: [] },
  { id: "quant-compound-interest", name: "Compound Interest", icon: "🏦", color: "bg-green-700", category: "Aptitude", topics: [] },
  { id: "quant-time-work", name: "Time & Work", icon: "⏳", color: "bg-cyan-600", category: "Aptitude", topics: [] },
  { id: "quant-time-distance", name: "Time, Speed & Distance", icon: "🚗", color: "bg-blue-500", category: "Aptitude", topics: [] },
  { id: "quant-pipes-cisterns", name: "Pipes & Cisterns", icon: "🚰", color: "bg-indigo-500", category: "Aptitude", topics: [] },
  { id: "quant-profit-loss", name: "Profit & Loss", icon: "📈", color: "bg-red-500", category: "Aptitude", topics: [] },
  { id: "quant-partnership", name: "Partnerships", icon: "🤝", color: "bg-gray-500", category: "Aptitude", topics: [] },
  { id: "quant-ages", name: "Problems on Ages", icon: "🎂", color: "bg-purple-600", category: "Aptitude", topics: [] },
  { id: "quant-trains", name: "Problems on Trains", icon: "🚆", color: "bg-orange-600", category: "Aptitude", topics: [] },
  { id: "quant-boats-streams", name: "Boats & Streams", icon: "🚤", color: "bg-blue-700", category: "Aptitude", topics: [] },
  { id: "quant-permutation-combination", name: "Permutations & Combinations", icon: "🎲", color: "bg-teal-700", category: "Aptitude", topics: [] },
  { id: "quant-probability", name: "Probability", icon: "🎯", color: "bg-purple-500", category: "Aptitude", topics: [] },
  { id: "quant-algebra", name: "Algebra", icon: "➕", color: "bg-green-600", category: "Aptitude", topics: [] },
  { id: "quant-geometry", name: "Geometry", icon: "📐", color: "bg-indigo-600", category: "Aptitude", topics: [] },
  { id: "quant-mensuration", name: "Mensuration", icon: "📏", color: "bg-yellow-500", category: "Aptitude", topics: [] },
  { id: "quant-trigonometry", name: "Trigonometry", icon: "📐", color: "bg-blue-500", category: "Aptitude", topics: [] },
  { id: "quant-logarithms", name: "Logarithms", icon: "📈", color: "bg-red-600", category: "Aptitude", topics: [] },
  { id: "quant-progressions", name: "AP & GP", icon: "🔄", color: "bg-green-700", category: "Aptitude", topics: [] },

  
  { id: "reasoning-puzzles", name: "Puzzles", icon: "🧩", color: "bg-yellow-500", category: "Reasoning", topics: [] },
  { id: "reasoning-seating-arrangement", name: "Seating Arrangement", icon: "🪑", color: "bg-purple-500", category: "Reasoning", topics: [] },
  { id: "reasoning-blood-relations", name: "Blood Relations", icon: "🧬", color: "bg-red-500", category: "Reasoning", topics: [] },
  { id: "reasoning-syllogisms", name: "Syllogisms", icon: "⚖️", color: "bg-indigo-500", category: "Reasoning", topics: [] },
  { id: "reasoning-series", name: "Number & Letter Series", icon: "🔢", color: "bg-blue-500", category: "Reasoning", topics: [] },
  { id: "reasoning-analogy", name: "Analogy", icon: "🔄", color: "bg-green-500", category: "Reasoning", topics: [] },
  { id: "reasoning-coding-decoding", name: "Coding & Decoding", icon: "📝", color: "bg-cyan-500", category: "Reasoning", topics: [] },
  { id: "reasoning-data-sufficiency", name: "Data Sufficiency", icon: "📊", color: "bg-orange-500", category: "Reasoning", topics: [] },
  { id: "reasoning-clocks-calendars", name: "Clocks & Calendars", icon: "⏰", color: "bg-gray-600", category: "Reasoning", topics: [] },
  { id: "reasoning-direction-sense", name: "Direction Sense", icon: "🧭", color: "bg-blue-700", category: "Reasoning", topics: [] },
  { id: "reasoning-logical-deductions", name: "Logical Deductions", icon: "🧠", color: "bg-purple-700", category: "Reasoning", topics: [] },

  
  { id: "verbal-reading-comprehension", name: "Reading Comprehension", icon: "📖", color: "bg-green-600", category: "Verbal", topics: [] },
  { id: "verbal-synonyms", name: "Synonyms", icon: "🔄", color: "bg-blue-500", category: "Verbal", topics: [] },
  { id: "verbal-antonyms", name: "Antonyms", icon: "🔁", color: "bg-red-500", category: "Verbal", topics: [] },
  { id: "verbal-error-detection", name: "Error Detection", icon: "🚨", color: "bg-orange-500", category: "Verbal", topics: [] },
  { id: "verbal-sentence-improvement", name: "Sentence Improvement", icon: "✏️", color: "bg-purple-500", category: "Verbal", topics: [] },
  { id: "verbal-parajumbles", name: "Para Jumbles", icon: "🪢", color: "bg-indigo-600", category: "Verbal", topics: [] },
  { id: "verbal-fill-in-the-blanks", name: "Fill in the Blanks", icon: "📝", color: "bg-yellow-500", category: "Verbal", topics: [] },
  { id: "verbal-one-word", name: "One Word Substitution", icon: "🗣️", color: "bg-teal-600", category: "Verbal", topics: [] },
  { id: "verbal-idioms", name: "Idioms & Phrases", icon: "💬", color: "bg-pink-500", category: "Verbal", topics: [] },
  { id: "verbal-active-passive", name: "Active & Passive Voice", icon: "🔄", color: "bg-blue-700", category: "Verbal", topics: [] },
  { id: "verbal-direct-indirect", name: "Direct & Indirect Speech", icon: "🗨️", color: "bg-gray-600", category: "Verbal", topics: [] },

  
  { 
    id: "resume-writing", 
    name: "Resume Writing", 
    icon: "📄", 
    color: "bg-gray-600", 
    category: "Interview Prep", 
    topics: [
      { id: "resume-structure", name: "Resume Structure & Format" },
      { id: "resume-content", name: "Content Writing" },
      { id: "resume-keywords", name: "Keywords & ATS Optimization" },
      { id: "resume-experience", name: "Work Experience Section" },
      { id: "resume-skills", name: "Skills Section" },
      { id: "resume-projects", name: "Projects Section" },
      { id: "resume-education", name: "Education Section" },
      { id: "resume-objective", name: "Objective vs Summary" },
      { id: "resume-templates", name: "Templates & Design" },
      { id: "resume-mistakes", name: "Common Mistakes" },
      { id: "resume-tailoring", name: "Tailoring for Jobs" },
      { id: "resume-portfolio", name: "Portfolio Integration" },
    ] 
  },
  { 
    id: "group-discussion", 
    name: "Group Discussion", 
    icon: "🗣️", 
    color: "bg-yellow-600", 
    category: "Interview Prep", 
    topics: [
      { id: "gd-basics", name: "GD Fundamentals" },
      { id: "gd-types", name: "Types of GD" },
      { id: "gd-initiation", name: "Initiating Discussion" },
      { id: "gd-participation", name: "Active Participation" },
      { id: "gd-leadership", name: "Leadership Skills" },
      { id: "gd-listening", name: "Active Listening" },
      { id: "gd-conflict-resolution", name: "Handling Conflicts" },
      { id: "gd-body-language", name: "Body Language" },
      { id: "gd-topics", name: "Common GD Topics" },
      { id: "gd-evaluation", name: "Evaluation Criteria" },
      { id: "gd-dos-donts", name: "Do's and Don'ts" },
      { id: "gd-practice", name: "Practice Strategies" },
    ] 
  },
  { 
    id: "hr-interview", 
    name: "HR Interview", 
    icon: "🤝", 
    color: "bg-green-500", 
    category: "Interview Prep", 
    topics: [
      { id: "hr-common-questions", name: "Common HR Questions" },
      { id: "hr-tell-me-about-yourself", name: "Tell Me About Yourself" },
      { id: "hr-strengths-weaknesses", name: "Strengths & Weaknesses" },
      { id: "hr-why-company", name: "Why This Company?" },
      { id: "hr-career-goals", name: "Career Goals" },
      { id: "hr-salary-negotiation", name: "Salary Negotiation" },
      { id: "hr-gap-explanation", name: "Explaining Gaps" },
      { id: "hr-behavioral-questions", name: "Behavioral Questions" },
      { id: "hr-conflict-resolution", name: "Conflict Resolution" },
      { id: "hr-leadership", name: "Leadership Examples" },
      { id: "hr-questions-to-ask", name: "Questions to Ask HR" },
      { id: "hr-follow-up", name: "Follow-up Process" },
    ] 
  },
  { 
    id: "technical-interview", 
    name: "Technical Interview", 
    icon: "💻", 
    color: "bg-blue-600", 
    category: "Interview Prep", 
    topics: [
      { id: "tech-coding-problems", name: "Coding Problems" },
      { id: "tech-system-design", name: "System Design" },
      { id: "tech-data-structures", name: "Data Structures" },
      { id: "tech-algorithms", name: "Algorithms" },
      { id: "tech-database-questions", name: "Database Questions" },
      { id: "tech-oops-concepts", name: "OOP Concepts" },
      { id: "tech-project-discussion", name: "Project Discussion" },
      { id: "tech-problem-solving", name: "Problem-Solving Approach" },
      { id: "tech-coding-best-practices", name: "Coding Best Practices" },
      { id: "tech-testing-debugging", name: "Testing & Debugging" },
      { id: "tech-technology-trends", name: "Technology Trends" },
      { id: "tech-whiteboard-coding", name: "Whiteboard Coding" },
    ] 
  },
  { 
    id: "behavioral-interview", 
    name: "Behavioral Interview", 
    icon: "🧠", 
    color: "bg-purple-500", 
    category: "Interview Prep", 
    topics: [
      { id: "behavioral-star-method", name: "STAR Method" },
      { id: "behavioral-teamwork", name: "Teamwork Examples" },
      { id: "behavioral-leadership", name: "Leadership Situations" },
      { id: "behavioral-problem-solving", name: "Problem-Solving Stories" },
      { id: "behavioral-failure-learning", name: "Failure & Learning" },
      { id: "behavioral-innovation", name: "Innovation & Creativity" },
      { id: "behavioral-pressure-handling", name: "Handling Pressure" },
      { id: "behavioral-adaptability", name: "Adaptability" },
      { id: "behavioral-communication", name: "Communication Skills" },
      { id: "behavioral-customer-focus", name: "Customer Focus" },
      { id: "behavioral-ethics", name: "Ethical Dilemmas" },
      { id: "behavioral-preparation", name: "Story Preparation" },
    ] 
  },
  { 
    id: "communication-skills", 
    name: "Communication Skills", 
    icon: "🗨️", 
    color: "bg-pink-500", 
    category: "Soft Skills", 
    topics: [
      { id: "comm-verbal", name: "Verbal Communication" },
      { id: "comm-non-verbal", name: "Non-Verbal Communication" },
      { id: "comm-listening", name: "Active Listening" },
      { id: "comm-public-speaking", name: "Public Speaking" },
      { id: "comm-written", name: "Written Communication" },
      { id: "comm-presentation", name: "Presentation Skills" },
      { id: "comm-interpersonal", name: "Interpersonal Skills" },
      { id: "comm-feedback", name: "Giving & Receiving Feedback" },
      { id: "comm-cultural-awareness", name: "Cultural Awareness" },
      { id: "comm-digital", name: "Digital Communication" },
      { id: "comm-persuasion", name: "Persuasion & Influence" },
      { id: "comm-networking", name: "Networking Skills" },
    ] 
  },
  
 { id: "gk-current-affairs", name: "Current Affairs", icon: "📰", color: "bg-red-500", category: "GK", topics: [] },
 { id: "gk-static", name: "Static GK", icon: "📚", color: "bg-blue-600", category: "GK", topics: [{ id: "gk-history", name: "History" }, { id: "gk-geography", name: "Geography" }, { id: "gk-polity", name: "Polity" }, { id: "gk-art-culture", name: "Art & Culture" }] },
 { id: "gk-business", name: "Business & Economy", icon: "💹", color: "bg-green-500", category: "GK", topics: [{ id: "gk-finance", name: "Finance" }, { id: "gk-banking", name: "Banking" }, { id: "gk-budget", name: "Budget & Policies" }] },
 { id: "gk-science-tech", name: "Science & Technology", icon: "🔬", color: "bg-purple-500", category: "GK", topics: [{ id: "gk-space", name: "Space Exploration" }, { id: "gk-biotechnology", name: "Biotechnology" }, { id: "gk-it", name: "Information Technology" }] },
 { id: "gk-awards", name: "Awards & Honors", icon: "🏆", color: "bg-yellow-500", category: "GK", topics: [] },
 { id: "gk-sports", name: "Sports", icon: "🏅", color: "bg-blue-400", category: "GK", topics: [] },
 { id: "gk-constitution", name: "Indian Constitution & Polity", icon: "📜", color: "bg-indigo-600", category: "GK", topics: [] },
   { id: "gk-environment", name: "Environment & Ecology", icon: "🌱", color: "bg-green-700", category: "GK", topics: [] },


























{
  id: "cybersecurity",
  name: "Cybersecurity",
  icon: "🛡️",
  color: "bg-red-700",
  category: "Security",
  topics: [
    { id: "cyber-basics", name: "Cybersecurity Basics" },
    { id: "cyber-cryptography", name: "Cryptography" },
    { id: "cyber-network-security", name: "Network Security" },
    { id: "cyber-web-security", name: "Web Security" },
    { id: "cyber-malware", name: "Malware & Attacks" },
    { id: "cyber-penetration", name: "Penetration Testing" },
    { id: "cyber-incident-response", name: "Incident Response" },
    { id: "cyber-forensics", name: "Digital Forensics" },
    { id: "cyber-cloud-security", name: "Cloud Security" },
    { id: "cyber-iot", name: "IoT Security" },
    { id: "cyber-blockchain-security", name: "Blockchain Security" },
    { id: "cyber-standards", name: "Security Standards & Compliance" }
  ]
},

{
  id: "blockchain",
  name: "Blockchain & Web3",
  icon: "⛓️",
  color: "bg-gray-800",
  category: "Blockchain",
  topics: [
    { id: "blockchain-basics", name: "Blockchain Basics" },
    { id: "blockchain-ethereum", name: "Ethereum" },
    { id: "blockchain-solidity", name: "Solidity" },
    { id: "blockchain-smart-contracts", name: "Smart Contracts" },
    { id: "blockchain-nfts", name: "NFTs" },
    { id: "blockchain-defi", name: "DeFi (Decentralized Finance)" },
    { id: "blockchain-consensus", name: "Consensus Mechanisms" },
    { id: "blockchain-hyperledger", name: "Hyperledger" },
    { id: "blockchain-ipfs", name: "IPFS" },
    { id: "blockchain-dapps", name: "DApps (Decentralized Apps)" },
    { id: "blockchain-web3", name: "Web3.js & Ethers.js" },
    { id: "blockchain-security", name: "Blockchain Security" }
  ]
},

{
  id: "data-science",
  name: "Data Science & Big Data",
  icon: "📊",
  color: "bg-blue-700",
  category: "Data",
  topics: [
    { id: "ds-data-analysis", name: "Data Analysis" },
    { id: "ds-visualization", name: "Data Visualization" },
    { id: "ds-statistics", name: "Statistics for Data Science" },
    { id: "ds-pandas", name: "Pandas & NumPy" },
    { id: "ds-sql", name: "SQL for Data Science" },
    { id: "ds-big-data", name: "Big Data Basics" },
    { id: "ds-hadoop", name: "Hadoop Ecosystem" },
    { id: "ds-spark", name: "Apache Spark" },
    { id: "ds-data-cleaning", name: "Data Cleaning & Preprocessing" },
    { id: "ds-data-engineering", name: "Data Engineering" },
    { id: "ds-ml", name: "Machine Learning for Data Science" },
    { id: "ds-cloud", name: "Cloud Data Platforms (AWS, GCP, Azure)" }
  ]
},

{
  id: "software-engineering",
  name: "Software Engineering",
  icon: "🛠️",
  color: "bg-green-600",
  category: "Engineering",
  topics: [
    { id: "se-sdlc", name: "Software Development Life Cycle" },
    { id: "se-agile", name: "Agile & Scrum" },
    { id: "se-version-control", name: "Version Control (Git)" },
    { id: "se-ci-cd", name: "CI/CD Pipelines" },
    { id: "se-design-patterns", name: "Design Patterns" },
    { id: "se-clean-code", name: "Clean Code Principles" },
    { id: "se-testing", name: "Unit & Integration Testing" },
    { id: "se-refactoring", name: "Code Refactoring" },
    { id: "se-documentation", name: "Documentation Best Practices" },
    { id: "se-microservices", name: "Microservices Architecture" },
    { id: "se-scalability", name: "Scalability & Performance" },
    { id: "se-system-design", name: "System Design" }
  ]
}
]

export default techTopics;

